version: '3.8'

services:
  postooo:  # Changed the service name to postooo
    image: postgres:latest
    container_name: postooo  # Changed container name to postooo
    restart: always
    environment:
      POSTGRES_USER: user             
      POSTGRES_PASSWORD: userpassword  
      POSTGRES_DB: project3DB         
    volumes:
      - pg_data:/var/lib/postgresql/data 
    networks:
      - my_network
    ports:
      - "5432:5432"                  

  grafooo:  # Changed the service name to grafooo
    image: grafana/grafana
    container_name: grafooo  # Changed container name to grafooo
    restart: always
    networks:
      - my_network
    ports:
      - "3000:3000"                   
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  

networks:
  my_network:
    driver: bridge

volumes:
  pg_data:
